// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpbB8kHsNMqiDO-a1zy8jGrOYFY6pisE',
    appId: '1:59645882998:web:569516f7d9aeec41d8e557',
    messagingSenderId: '59645882998',
    projectId: 'busticketingapp-11ef7',
    authDomain: 'busticketingapp-11ef7.firebaseapp.com',
    storageBucket: 'busticketingapp-11ef7.firebasestorage.app',
    measurementId: 'G-9MQP9MZXCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-7JRgIUrk6v3FP5dbLlGzCUx98YeLkc',
    appId: '1:59645882998:android:c4004c35e49ac974d8e557',
    messagingSenderId: '59645882998',
    projectId: 'busticketingapp-11ef7',
    storageBucket: 'busticketingapp-11ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIl6HKtZiBhMGpKS5tHii4ced-r0PTyQ',
    appId: '1:59645882998:ios:e5640fde70cad9f0d8e557',
    messagingSenderId: '59645882998',
    projectId: 'busticketingapp-11ef7',
    storageBucket: 'busticketingapp-11ef7.firebasestorage.app',
    iosBundleId: 'com.example.busTicketingApp',
  );
}
